title: OSINT Notes
description: Open source intelligence tradecraft, casework methodology, and tooling notes.
author: jynx_84999

url: "https://francose.github.io"
baseurl: "/osint-blog"

theme: minima
minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:year/:month/:title/
timezone: America/New_York

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
